use cosmwasm_schema::{cw_serde, QueryResponses};
use cosmwasm_std::Coin;

use crate::state::RequestStatus;

#[cw_serde]
pub struct MigrateMsg {
}

/// Instantiated by the factory via `instantiate2`. Defined in the shared crate
/// so the factory (producer) and forwarder (consumer) share one JSON schema.
pub use forwarder_factory_shared::ForwarderInstantiateMsg as InstantiateMsg;

#[cw_serde]
pub enum ExecuteMsg {
    TransferCall {
        mint_tx_hash: String,
        transfer_coin: Coin,
        hook_data: String,
        destination_channel: String,
    },
    Refund {
        mint_tx_hash: String,
    },
    Abandon {
        mint_tx_hash: String,
    },
}

#[cw_serde]
#[derive(QueryResponses)]
pub enum QueryMsg {
    #[returns(ConfigResponse)]
    Config {},

    #[returns(RequestListResponse)]
    Requests {
        start_after: Option<u64>,
        limit: Option<u32>,
        order: Option<RequestOrder>,
    },

    #[returns(RequestResponse)]
    RequestByMintTxHash { mint_tx_hash: String },
}

/// No-op migrate payload (cw2 versioning hook).
#[cw_serde]
pub struct MigrateMsg {}

#[cw_serde]
pub enum RequestOrder {
    Asc,
    Desc,
}

/// Merged view: local route fields + shared config resolved from the factory.
#[cw_serde]
pub struct ConfigResponse {
    pub factory: String,
    pub sender_addr: String,
    pub recipient_addr: String,
    pub dest_chain: String,
    // Resolved from the parent factory at query time:
    pub skip_relayer_addr: String,
    pub skip_entrypoint_addr: String,
    pub refund_addr: String,
    pub owner: String,
}

#[cw_serde]
pub struct RequestItem {
    pub id: u64,
    pub mint_tx_hash: String,
    pub transfer_coin: Coin,
    pub source_tx_height: u64,
    pub source_tx_index: Option<u32>,
    pub destination_channel: String,
    pub status: RequestStatus,
    pub error_msg: Option<String>,
}

#[cw_serde]
pub struct RequestListResponse {
    pub requests: Vec<RequestItem>,
}

#[cw_serde]
pub struct RequestResponse {
    pub request: RequestItem,
}

// This file was generated by schema-generator
use cosmwasm_schema::cw_serde;
use cosmwasm_std::{Addr, Binary, Coin, Uint128};

// TODO: This is a placeholder for the Cw20ReceiveMsg,
// which should be defined in the cw20 crate.
#[cw_serde]
pub struct Cw20ReceiveMsg {
    pub sender: String,
    pub amount: Uint128,
    pub msg: Binary,
}

#[cw_serde]
pub enum Asset {
    Native(Coin),
    Cw20(Addr),
}

#[cw_serde]
pub enum Swap {
    SwapExactAssetIn(SwapExactAssetIn),
    SwapExactAssetOut(SwapExactAssetOut),
}

#[cw_serde]
pub struct SwapExactAssetIn {
    pub swap_venue_name: String,
    pub operations: Vec<SwapOperation>,
}

#[cw_serde]
pub struct SwapExactAssetOut {
    pub swap_venue_name: String,
    pub operations: Vec<SwapOperation>,
}

#[cw_serde]
pub struct SwapOperation {
    pub pool: String,
    pub denom_in: String,
    pub denom_out: String,
}

#[cw_serde]
pub enum Action {
    Transfer(Transfer),
    IbcTransfer(IbcTransfer),
    ContractCall(ContractCall),
}

#[cw_serde]
pub struct Transfer {
    pub to_address: String,
}

#[cw_serde]
pub struct IbcTransfer {
    pub channel: String,
    pub to_address: String,
    pub fee: Option<IbcFee>,
}

#[cw_serde]
pub struct IbcFee {
    pub amount: Vec<Coin>,
    pub gas_limit: Option<String>,
}

#[cw_serde]
pub struct ContractCall {
    pub contract_address: String,
    pub msg: Binary,
}

#[cw_serde]
pub struct Affiliate {
    pub basis_points_fee: Uint128,
    pub address: String,
}

#[cw_serde]
#[allow(clippy::large_enum_variant)]
pub enum SkipExecuteMsg {
    Receive(Cw20ReceiveMsg),
    SwapAndActionWithRecover {
        sent_asset: Option<Asset>,
        user_swap: Swap,
        min_asset: Asset,
        timeout_timestamp: u64,
        post_swap_action: Action,
        affiliates: Vec<Affiliate>,
        recovery_addr: Addr,
    },
    SwapAndAction {
        sent_asset: Option<Asset>,
        user_swap: Swap,
        min_asset: Asset,
        timeout_timestamp: u64,
        post_swap_action: Action,
        affiliates: Vec<Affiliate>,
    },
    UserSwap {
        swap: Swap,
        min_asset: Asset,
        remaining_asset: Asset,
        affiliates: Vec<Affiliate>,
    },
    PostSwapAction {
        min_asset: Asset,
        timeout_timestamp: u64,
        post_swap_action: Action,
        exact_out: bool,
    },
    Action {
        sent_asset: Option<Asset>,
        timeout_timestamp: u64,
        action: Action,
        exact_out: bool,
        min_asset: Option<Asset>,
    },
    ActionWithRecover {
        sent_asset: Option<Asset>,
        timeout_timestamp: u64,
        action: Action,
        exact_out: bool,
        min_asset: Option<Asset>,
        recovery_addr: Addr,
    },
}
